sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        AS8WXTm+VcUhjd9s8ulczOAFXwSodmromahNCIq7rQ35iXxTmIV0Fln/vKHs+x82GJ1X7IUyvPK92xzX17TPHT2iQdgY9em9Qripo6JLHwOvC2rweMn3VYrzpuleewbslCedFjiAvW4rLDEEJ3rQpU2NoDff8vXwWdiKXkCv4CcFd7G5AqnhOE5ULzRFdf+fwItfCoZQG+4QmlNKaJn3fJerxrtuynn1YaP4GyA6OnVhq6PdAYczr1QXzUoINXc/5HUW7fvYNuHa4s+R1vB63dh/WzGvemhFFt6p5ZeR0aaYF6tV4ixtKcW8A2hqxtrfe1rxNH+pNbYSViys9ZrPYoHm6H+cfg+x3QJvOtDXJLXPahwGc83SURSp8iJiTw39Wx85d6uEkSvf9zagxmdehCoOMU3dlSAQNe3j7DTGznRxUDqVh1hMlweXzx/oWNrAsMgSiAdC+iolWjXdOg3W8xfoiENd8SIVDMzaeFPwx44bqKGKTaE2BNVUsHhVIErs1jgLdthnUUevcCyUtadqJ9uUFuU/JKQDSuXc1zDayXs4hJGFleR4y9czknHsPsWbadJyORwy1YM1+PuUcrYQTqWVTIVXQrD49V9LF3w+jW/XvcaKf9emrqe6eLVdfmPNhx3ZMQkpkAQoyZJ5otf114sCRCb0+uX1FpkrL80umz0=
    - secure: >-
        mzuORig/o8TulOEHvI3yaM3ihNCQDCExPonOojjYK+LFLb8WX0ZR8ZwfJS3w8TJrYWfU3eWgXGYJQBoDtp2WS5sRh9jxke39OZZY4HP7WebxeEFxGBxAELVEAhNEFg1PxOXlAaHOUHW35Y/HnwdBbE2hFYL91Mlk2Md8rPIPUU3UkuaECtiBCYFu72NPlgUYwtLnDMX/O9TFDJG7e9BWvYbHKHRYnwqx1EcDaXkwnXSpA9vM4gUbWcllWLyrRJhyBrYg7cQZ9g2hwsr6D9z1xBfuNdpTCHPFJXiM97dJ0j3x02lFKCXELFT6kWwQhvgHDtKDWJ+esc/yRNwTDwWlJTFuTDPdJBrlCb97kaaJV9qJHA/qC1XM9oyfuV8oMvemM8U3bcm+6zfJO+BICuAyrlhNdKL036A6lg2QsG2Sstzfa9v568EeiVsTb6KTQl7ctiA22KrYpx3CaZnWGZmBzmERZAhEeip3qfoxOgacey4FzgtVPoF1rrwuUzVztTTqRViCPktrmXnyOzDNjymMWKprTuyY72ZaDFFljOsmwZ/eC4HgSqV9+ynW13XBSUcZDVUG7W2mICZP6aynowiLVo0XzBeXSroVljvEhsYZjTwIROw1BGCRbqc2VFJnlxtcPEj72TFbs2ZcbhzxsEQ3TWPPN1wdVdNmOvKoP8aFHdM=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
