sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        BwfANhu2NrGFF74Clv1w5iG52rVPn38P3/fhIEMNOW0p2GNa3+JRsr9Y9sU6vqvefbw2xmYzzce7wnFV2MaiUVc7TiiWnmtgEoz3dXyX+BSWAdMN80miYB4Hy+yf+m8IXd/C63eLGmAP6pDHcuUBS/lRTEIFB5ETarUDaPafT+TB7H2mgG1I6D1o39CwYKIgZGAwXwbm/jSCFOwDRLA9TFbOC0gMxULWPNf4FpNJMCcz3d5eXgk5R861VBMOqX/32bKswGALe4k2zVBLoCZfCOlJb84zBMhxT8/I4WVayhAl9X2yfpojGzYObpd8Xp2xicQ+qRqalNzw79ghWk+lyxqu0E2bT8RxQxizsHti11w3TQqbD1JUGTIqLjybq4WkhnLMbIgWsKS++fv047/LxF/8z/YLQ+WlXcVYH795ivqqBuCumbtTzXJ51SpGqw+ID4w7dkvNoBR6ZML/mvCMn0rmIqYd6049COmA3hlGxYKdcVlEVbqsLnexnZRovpXVvp4ZSGC4oMg8pYAoi1sIK774qPlG3tkIgfJTC4P17U8J9YbZ9BTJYs9VF0PGijxgPlCtPnm0rJs2GLF6aOAk7NMDyc7s6PBdZvlm7Ai/8QQiZx4LeQD/qcBVmlGxKyggKejG/bsvUAlrMsCobkHBBkevZbXFy+JNz2dsfIRdXM0=
    - secure: >-
        jJED4UaGibPrykCZWxFjVtBg/RlobPMa3VGbS+Ll+6zjxuAhRUJ5zA2WjlgLkEhaBJPllfXJl9Cuj7lNE5lmHzrybzHm4vYWIR7yEGB6PLmwZQoAAUuthl0//Mrx32V1ZBKH1uRDLOcLJn73+P1IIR+JgvbOgISSwwfzEdjIlQ6t3GmSs32PXuXbsAbpPJVrlm7iocxangZGRE+fc4yjAG5QwsKYveiwZFCuIttepcaO+5fpolnNR/9VNiYzhIUVGgBfKRlg4RXZ2NdLJVYlwWDer/cDE9nVYaNJ2YtUlwswWH7Q4rsaZGEeK0xJt9nITyoMuSyeWj6Vo7UK7ZqfdVRlSYdl6PdN0Q62Bj4dAEw08pwANXm9mATmyIbZwKTLdW0+Wv6qfvdZWOeTqnehyn8AsJg1OYi/F3xLnAzKsqGayjFk+ttqut8D1cFAxjWSWLw5ynaCTQ5TKmc8mhJ6o6fvuT0F7mThYzhGt9NRTUL3FMhCR02JoSOEUuJy/8UCXrs87NdANTLX9hnKCCZHu9kHDPVe0on5+y2XOighPVT3ylrAZ9olGW5rMo2a7dyvpHXgl4/tgj4GnVa2C4wC+yN1K/7m8Ty8WYGIn16xPWf4U5Jv1Odc6h1XO9sfGIM4sb8TQPr6GVAYbuJRbEZkTaSSxaubjYV/g7elfeXDIFw=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
